import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { motion } from "framer-motion";
import { Target, Flame, Clock, ChevronRight, Check } from "lucide-react";
import { PageHeader, Panel } from "@/components/widgets";
import { useIntelligence, useIntelligenceActions } from "@/lib/intelligence";
import type { MissionPriority } from "@/lib/mock-data";

export const Route = createFileRoute("/missions")({
  head: () => ({
    meta: [
      { title: "Missions — Scholaris" },
      { name: "description", content: "ROI-ranked academic missions generated by the intelligence engine." },
    ],
  }),
  component: MissionsCenter,
});

const priorityTone: Record<MissionPriority, string> = {
  critical: "bg-destructive/15 text-destructive border-destructive/30",
  high: "bg-warning/15 text-warning border-warning/30",
  medium: "bg-primary/15 text-primary border-primary/30",
  low: "bg-muted text-muted-foreground border-border",
};

function MissionsCenter() {
  const { missions, sessions } = useIntelligence();
  const { runMission } = useIntelligenceActions();
  const [filter, setFilter] = useState<"all" | MissionPriority>("all");

  const active = missions.filter((m) => !m.completed);
  const filtered = filter === "all" ? active : active.filter((m) => m.priority === filter);
  const totalMinutes = filtered.reduce((sum, m) => sum + m.estimatedMinutes, 0);

  const todayStart = new Date();
  todayStart.setHours(0, 0, 0, 0);
  const completedToday = sessions.filter((s) => s.timestamp >= todayStart.getTime());
  const completedMinutes = completedToday.reduce((a, s) => a + s.duration, 0);
  const masteryGained = completedToday.reduce((a, s) => a + s.gain, 0);

  return (
    <div>
      <PageHeader
        eyebrow="Missions"
        title="Missions Center"
        description="Each mission is generated by the intelligence engine — ranked by ROI and academic urgency."
        actions={
          <div className="inline-flex items-center gap-1 h-9 px-3 rounded-md border border-border bg-card text-xs text-muted-foreground">
            <Clock className="h-3 w-3" /> {totalMinutes}m total
          </div>
        }
      />

      <div className="flex flex-wrap gap-2 mb-5">
        {(["all", "critical", "high", "medium", "low"] as const).map((p) => (
          <button
            key={p}
            onClick={() => setFilter(p)}
            className={`px-3 h-8 rounded-md text-xs font-medium capitalize transition-colors cursor-pointer ${
              filter === p ? "bg-primary text-primary-foreground" : "bg-card border border-border text-muted-foreground hover:text-foreground"
            }`}
          >
            {p} {p !== "all" && <span className="ml-1 opacity-60">{active.filter((m) => m.priority === p).length}</span>}
          </button>
        ))}
      </div>

      <div className="grid lg:grid-cols-2 gap-3">
        {filtered.map((m, i) => (
          <motion.div
            key={m.id}
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.03 }}
            className="group rounded-xl border border-border bg-card p-5 hover:border-border/100 transition-all"
          >
            <div className="flex items-start gap-4">
              <div className={`h-10 w-10 shrink-0 rounded-lg grid place-items-center border ${priorityTone[m.priority]}`}>
                {m.priority === "critical" ? <Flame className="h-4 w-4" /> : <Target className="h-4 w-4" />}
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex flex-wrap items-center gap-2 mb-1.5">
                  <span className={`text-[10px] uppercase tracking-wider font-semibold px-1.5 py-0.5 rounded ${priorityTone[m.priority]}`}>{m.priority}</span>
                  <span className="text-[10px] uppercase tracking-wider font-semibold text-muted-foreground">{m.type}</span>
                  <span className="text-xs text-muted-foreground">· {m.subjectName}</span>
                </div>
                <h3 className="text-sm font-semibold tracking-tight">{m.title}</h3>
                <p className="text-xs text-muted-foreground mt-1 leading-relaxed">{m.description}</p>

                <div className="mt-3 p-2.5 rounded-md bg-muted/40 border border-border/40">
                  <div className="text-[10px] uppercase tracking-wider font-semibold text-muted-foreground mb-0.5">Reason</div>
                  <div className="text-xs">{m.reason}</div>
                </div>

                <div className="flex items-center justify-between mt-4">
                  <div className="flex items-center gap-4 text-xs text-muted-foreground">
                    <span className="flex items-center gap-1"><Clock className="h-3 w-3" />{m.estimatedMinutes}m</span>
                    <span className="text-success font-medium">ROI {m.roiScore}</span>
                    {m.dueBy && <span className="text-warning capitalize">Due {m.dueBy}</span>}
                  </div>
                  <button
                    onClick={() => runMission(m.id)}
                    className="inline-flex items-center gap-1 text-xs font-medium text-primary hover:underline cursor-pointer"
                  >
                    Run mission <ChevronRight className="h-3 w-3" />
                  </button>
                </div>
              </div>
            </div>
          </motion.div>
        ))}
        {filtered.length === 0 && (
          <div className="col-span-full text-sm text-muted-foreground py-12 text-center">
            No missions in this priority band. The intelligence engine is calibrated.
          </div>
        )}
      </div>

      <Panel title="Completed today" className="mt-6">
        <div className="flex items-center gap-3 text-sm text-muted-foreground">
          <div className="h-8 w-8 rounded-full bg-success/15 text-success grid place-items-center"><Check className="h-4 w-4" /></div>
          <span>
            {completedToday.length} session{completedToday.length === 1 ? "" : "s"} completed · {completedMinutes} minutes invested · <span className="text-success">+{masteryGained}% mastery gained</span>
          </span>
        </div>
      </Panel>
    </div>
  );
}
