/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/_app/route'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/_app/index'
import { Route as AuthenticatedAppTodayRouteImport } from './routes/_authenticated/_app/today'
import { Route as AuthenticatedAppSessionsRouteImport } from './routes/_authenticated/_app/sessions'
import { Route as AuthenticatedAppSessionRouteImport } from './routes/_authenticated/_app/session'
import { Route as AuthenticatedAppRoiRouteImport } from './routes/_authenticated/_app/roi'
import { Route as AuthenticatedAppRiskRouteImport } from './routes/_authenticated/_app/risk'
import { Route as AuthenticatedAppRecommendationsRouteImport } from './routes/_authenticated/_app/recommendations'
import { Route as AuthenticatedAppMissionsRouteImport } from './routes/_authenticated/_app/missions'
import { Route as AuthenticatedAppMemoryRouteImport } from './routes/_authenticated/_app/memory'
import { Route as AuthenticatedAppMapRouteImport } from './routes/_authenticated/_app/map'
import { Route as AuthenticatedAppDiagnosticsRouteImport } from './routes/_authenticated/_app/diagnostics'
import { Route as AuthenticatedAppDataSafetyRouteImport } from './routes/_authenticated/_app/data-safety'
import { Route as AuthenticatedAppConceptsRouteImport } from './routes/_authenticated/_app/concepts'
import { Route as AuthenticatedAppCoachRouteImport } from './routes/_authenticated/_app/coach'
import { Route as AuthenticatedAppBattlefieldRouteImport } from './routes/_authenticated/_app/battlefield'
import { Route as AuthenticatedAppSubjectsIdRouteImport } from './routes/_authenticated/_app/subjects.$id'
import { Route as AuthenticatedAppConceptsIdRouteImport } from './routes/_authenticated/_app/concepts.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppTodayRoute = AuthenticatedAppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppSessionsRoute =
  AuthenticatedAppSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSessionRoute = AuthenticatedAppSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppRoiRoute = AuthenticatedAppRoiRouteImport.update({
  id: '/roi',
  path: '/roi',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppRiskRoute = AuthenticatedAppRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppRecommendationsRoute =
  AuthenticatedAppRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppMissionsRoute =
  AuthenticatedAppMissionsRouteImport.update({
    id: '/missions',
    path: '/missions',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppMemoryRoute = AuthenticatedAppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppMapRoute = AuthenticatedAppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppDiagnosticsRoute =
  AuthenticatedAppDiagnosticsRouteImport.update({
    id: '/diagnostics',
    path: '/diagnostics',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppDataSafetyRoute =
  AuthenticatedAppDataSafetyRouteImport.update({
    id: '/data-safety',
    path: '/data-safety',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppConceptsRoute =
  AuthenticatedAppConceptsRouteImport.update({
    id: '/concepts',
    path: '/concepts',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCoachRoute = AuthenticatedAppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppBattlefieldRoute =
  AuthenticatedAppBattlefieldRouteImport.update({
    id: '/battlefield',
    path: '/battlefield',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSubjectsIdRoute =
  AuthenticatedAppSubjectsIdRouteImport.update({
    id: '/subjects/$id',
    path: '/subjects/$id',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppConceptsIdRoute =
  AuthenticatedAppConceptsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppConceptsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedAppIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/import': typeof AuthenticatedImportRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/battlefield': typeof AuthenticatedAppBattlefieldRoute
  '/coach': typeof AuthenticatedAppCoachRoute
  '/concepts': typeof AuthenticatedAppConceptsRouteWithChildren
  '/data-safety': typeof AuthenticatedAppDataSafetyRoute
  '/diagnostics': typeof AuthenticatedAppDiagnosticsRoute
  '/map': typeof AuthenticatedAppMapRoute
  '/memory': typeof AuthenticatedAppMemoryRoute
  '/missions': typeof AuthenticatedAppMissionsRoute
  '/recommendations': typeof AuthenticatedAppRecommendationsRoute
  '/risk': typeof AuthenticatedAppRiskRoute
  '/roi': typeof AuthenticatedAppRoiRoute
  '/session': typeof AuthenticatedAppSessionRoute
  '/sessions': typeof AuthenticatedAppSessionsRoute
  '/today': typeof AuthenticatedAppTodayRoute
  '/concepts/$id': typeof AuthenticatedAppConceptsIdRoute
  '/subjects/$id': typeof AuthenticatedAppSubjectsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedAppIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/import': typeof AuthenticatedImportRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/battlefield': typeof AuthenticatedAppBattlefieldRoute
  '/coach': typeof AuthenticatedAppCoachRoute
  '/concepts': typeof AuthenticatedAppConceptsRouteWithChildren
  '/data-safety': typeof AuthenticatedAppDataSafetyRoute
  '/diagnostics': typeof AuthenticatedAppDiagnosticsRoute
  '/map': typeof AuthenticatedAppMapRoute
  '/memory': typeof AuthenticatedAppMemoryRoute
  '/missions': typeof AuthenticatedAppMissionsRoute
  '/recommendations': typeof AuthenticatedAppRecommendationsRoute
  '/risk': typeof AuthenticatedAppRiskRoute
  '/roi': typeof AuthenticatedAppRoiRoute
  '/session': typeof AuthenticatedAppSessionRoute
  '/sessions': typeof AuthenticatedAppSessionsRoute
  '/today': typeof AuthenticatedAppTodayRoute
  '/concepts/$id': typeof AuthenticatedAppConceptsIdRoute
  '/subjects/$id': typeof AuthenticatedAppSubjectsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteRouteWithChildren
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/_app/battlefield': typeof AuthenticatedAppBattlefieldRoute
  '/_authenticated/_app/coach': typeof AuthenticatedAppCoachRoute
  '/_authenticated/_app/concepts': typeof AuthenticatedAppConceptsRouteWithChildren
  '/_authenticated/_app/data-safety': typeof AuthenticatedAppDataSafetyRoute
  '/_authenticated/_app/diagnostics': typeof AuthenticatedAppDiagnosticsRoute
  '/_authenticated/_app/map': typeof AuthenticatedAppMapRoute
  '/_authenticated/_app/memory': typeof AuthenticatedAppMemoryRoute
  '/_authenticated/_app/missions': typeof AuthenticatedAppMissionsRoute
  '/_authenticated/_app/recommendations': typeof AuthenticatedAppRecommendationsRoute
  '/_authenticated/_app/risk': typeof AuthenticatedAppRiskRoute
  '/_authenticated/_app/roi': typeof AuthenticatedAppRoiRoute
  '/_authenticated/_app/session': typeof AuthenticatedAppSessionRoute
  '/_authenticated/_app/sessions': typeof AuthenticatedAppSessionsRoute
  '/_authenticated/_app/today': typeof AuthenticatedAppTodayRoute
  '/_authenticated/_app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/_app/concepts/$id': typeof AuthenticatedAppConceptsIdRoute
  '/_authenticated/_app/subjects/$id': typeof AuthenticatedAppSubjectsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/import'
    | '/onboarding'
    | '/battlefield'
    | '/coach'
    | '/concepts'
    | '/data-safety'
    | '/diagnostics'
    | '/map'
    | '/memory'
    | '/missions'
    | '/recommendations'
    | '/risk'
    | '/roi'
    | '/session'
    | '/sessions'
    | '/today'
    | '/concepts/$id'
    | '/subjects/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/import'
    | '/onboarding'
    | '/battlefield'
    | '/coach'
    | '/concepts'
    | '/data-safety'
    | '/diagnostics'
    | '/map'
    | '/memory'
    | '/missions'
    | '/recommendations'
    | '/risk'
    | '/roi'
    | '/session'
    | '/sessions'
    | '/today'
    | '/concepts/$id'
    | '/subjects/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/_app'
    | '/_authenticated/import'
    | '/_authenticated/onboarding'
    | '/_authenticated/_app/battlefield'
    | '/_authenticated/_app/coach'
    | '/_authenticated/_app/concepts'
    | '/_authenticated/_app/data-safety'
    | '/_authenticated/_app/diagnostics'
    | '/_authenticated/_app/map'
    | '/_authenticated/_app/memory'
    | '/_authenticated/_app/missions'
    | '/_authenticated/_app/recommendations'
    | '/_authenticated/_app/risk'
    | '/_authenticated/_app/roi'
    | '/_authenticated/_app/session'
    | '/_authenticated/_app/sessions'
    | '/_authenticated/_app/today'
    | '/_authenticated/_app/'
    | '/_authenticated/_app/concepts/$id'
    | '/_authenticated/_app/subjects/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_app/': {
      id: '/_authenticated/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/today': {
      id: '/_authenticated/_app/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedAppTodayRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/sessions': {
      id: '/_authenticated/_app/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedAppSessionsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/session': {
      id: '/_authenticated/_app/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof AuthenticatedAppSessionRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/roi': {
      id: '/_authenticated/_app/roi'
      path: '/roi'
      fullPath: '/roi'
      preLoaderRoute: typeof AuthenticatedAppRoiRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/risk': {
      id: '/_authenticated/_app/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof AuthenticatedAppRiskRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/recommendations': {
      id: '/_authenticated/_app/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof AuthenticatedAppRecommendationsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/missions': {
      id: '/_authenticated/_app/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof AuthenticatedAppMissionsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/memory': {
      id: '/_authenticated/_app/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AuthenticatedAppMemoryRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/map': {
      id: '/_authenticated/_app/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedAppMapRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/diagnostics': {
      id: '/_authenticated/_app/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof AuthenticatedAppDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/data-safety': {
      id: '/_authenticated/_app/data-safety'
      path: '/data-safety'
      fullPath: '/data-safety'
      preLoaderRoute: typeof AuthenticatedAppDataSafetyRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/concepts': {
      id: '/_authenticated/_app/concepts'
      path: '/concepts'
      fullPath: '/concepts'
      preLoaderRoute: typeof AuthenticatedAppConceptsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/coach': {
      id: '/_authenticated/_app/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedAppCoachRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/battlefield': {
      id: '/_authenticated/_app/battlefield'
      path: '/battlefield'
      fullPath: '/battlefield'
      preLoaderRoute: typeof AuthenticatedAppBattlefieldRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/subjects/$id': {
      id: '/_authenticated/_app/subjects/$id'
      path: '/subjects/$id'
      fullPath: '/subjects/$id'
      preLoaderRoute: typeof AuthenticatedAppSubjectsIdRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/concepts/$id': {
      id: '/_authenticated/_app/concepts/$id'
      path: '/$id'
      fullPath: '/concepts/$id'
      preLoaderRoute: typeof AuthenticatedAppConceptsIdRouteImport
      parentRoute: typeof AuthenticatedAppConceptsRoute
    }
  }
}

interface AuthenticatedAppConceptsRouteChildren {
  AuthenticatedAppConceptsIdRoute: typeof AuthenticatedAppConceptsIdRoute
}

const AuthenticatedAppConceptsRouteChildren: AuthenticatedAppConceptsRouteChildren =
  {
    AuthenticatedAppConceptsIdRoute: AuthenticatedAppConceptsIdRoute,
  }

const AuthenticatedAppConceptsRouteWithChildren =
  AuthenticatedAppConceptsRoute._addFileChildren(
    AuthenticatedAppConceptsRouteChildren,
  )

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppBattlefieldRoute: typeof AuthenticatedAppBattlefieldRoute
  AuthenticatedAppCoachRoute: typeof AuthenticatedAppCoachRoute
  AuthenticatedAppConceptsRoute: typeof AuthenticatedAppConceptsRouteWithChildren
  AuthenticatedAppDataSafetyRoute: typeof AuthenticatedAppDataSafetyRoute
  AuthenticatedAppDiagnosticsRoute: typeof AuthenticatedAppDiagnosticsRoute
  AuthenticatedAppMapRoute: typeof AuthenticatedAppMapRoute
  AuthenticatedAppMemoryRoute: typeof AuthenticatedAppMemoryRoute
  AuthenticatedAppMissionsRoute: typeof AuthenticatedAppMissionsRoute
  AuthenticatedAppRecommendationsRoute: typeof AuthenticatedAppRecommendationsRoute
  AuthenticatedAppRiskRoute: typeof AuthenticatedAppRiskRoute
  AuthenticatedAppRoiRoute: typeof AuthenticatedAppRoiRoute
  AuthenticatedAppSessionRoute: typeof AuthenticatedAppSessionRoute
  AuthenticatedAppSessionsRoute: typeof AuthenticatedAppSessionsRoute
  AuthenticatedAppTodayRoute: typeof AuthenticatedAppTodayRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppSubjectsIdRoute: typeof AuthenticatedAppSubjectsIdRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppBattlefieldRoute: AuthenticatedAppBattlefieldRoute,
  AuthenticatedAppCoachRoute: AuthenticatedAppCoachRoute,
  AuthenticatedAppConceptsRoute: AuthenticatedAppConceptsRouteWithChildren,
  AuthenticatedAppDataSafetyRoute: AuthenticatedAppDataSafetyRoute,
  AuthenticatedAppDiagnosticsRoute: AuthenticatedAppDiagnosticsRoute,
  AuthenticatedAppMapRoute: AuthenticatedAppMapRoute,
  AuthenticatedAppMemoryRoute: AuthenticatedAppMemoryRoute,
  AuthenticatedAppMissionsRoute: AuthenticatedAppMissionsRoute,
  AuthenticatedAppRecommendationsRoute: AuthenticatedAppRecommendationsRoute,
  AuthenticatedAppRiskRoute: AuthenticatedAppRiskRoute,
  AuthenticatedAppRoiRoute: AuthenticatedAppRoiRoute,
  AuthenticatedAppSessionRoute: AuthenticatedAppSessionRoute,
  AuthenticatedAppSessionsRoute: AuthenticatedAppSessionsRoute,
  AuthenticatedAppTodayRoute: AuthenticatedAppTodayRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppSubjectsIdRoute: AuthenticatedAppSubjectsIdRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
